### ISSUE TITLE
Switch workspace with three/four fingers

### ISSUE THREAD

**Issue by vothanhdat** [do-sch/gnome-shell-touchpad-window-move#1]
hi @do-sch, i really interesting with your gnome extension.  
Do you think is it possible for implement extension to switch workspace with three/four fingers responsively, like macbook or window.

Thanks.

**Comment by do-sch** [comment]
Switching workspaces with four fingers is already default behaviour in GNOME Shell on wayland session (if your touchpad supports gestures through libinput).
Futhermore there is already an extension, to enable switching workspaces with three fingers:
https://github.com/mpiannucci/gnome-shell-extended-gestures
