### ISSUE TITLE
3-finger windows resize?

### ISSUE THREAD

**Issue by srid** [do-sch/gnome-shell-touchpad-window-move#10]
It would be useful to add a gesture to resize the windows. Why? Because then you can move and resize windows all using the trackpad with one sequence of gestures. Is this possible with GNOME?

3-finger pinch already opens Activites; can that be used?

**Comment by do-sch** [comment]
In theory the three finger pinch gesture can be stolen from shell to be used for different things.
But you can resize a window horizontally as well as vertically. Which of the attributes do you want to be changed? Vertical or horizontal?
If you'd change both at once, you couldn't alter the window dimensions.

The only rational thing, that would be possible, is simulating Alt+F8 when pinching three fingers together. But honestly, I wouldn't use that. That just wouldn't be practical.

I'll close this issue for now, but keep it in mind in case I can think of something better.

**Comment by egormanga** [comment]
Maybe do the resizing when dragging with a modifier held (like LAlt)?
