### ISSUE TITLE
[Feature Request] Middle button window move

### ISSUE THREAD

**Issue by SelfRef** [do-sch/gnome-shell-touchpad-window-move#11]
Three-finger gesture is a great usability feature. I thought same can be added to mouse using middle mouse button/wheel so window could be moved by holding button and dragging the pointer (just like using `Window Action Key`).

By default three-fingers tap is already mapped as middle click so three-fingers gesture can as well be "backported" to mouse.

The only doubt I have is potential compatibility issues with e.g. games. I don't see any desktop case where wheel-drag is used nevertheless I think it should be disabled in settings by default.

**Comment by do-sch** [comment]
I do not think this is possible through an extension, as the middle mouse button press is in contrast to touchpad gestures directly delegated to single applications by Mutter. Therefore it can not be catched by the shell. To get this feature, someone needs to fork Mutter and provide an API.
