### ISSUE TITLE
Shift + three fingers --> jump to edge;     Ctrl + three fingers -- resize 

### ISSUE THREAD

**Issue by leszekdubiel** [do-sch/gnome-shell-touchpad-window-move#12]
Moving window with three fingers is great. 

I miss some more features: 

-- when you press Shift and move window with three finger it sould immediately jump to the edge of screen -- "Shift" means long jump

-- when you press Cntrl and drag window with three fingers then you resize -- lower or right edge moves with your fingers.

**Comment by do-sch** [comment]
I'd like to keep the extension slim. Gesturing the touchpad and pressing keys at the same time is too much in my opinion. If you want windows to move faster to the other end of the screen, you should change the move speed in Settings. I have already tried to resize the window using the pinch gesture. But that was too limited by my Mutter.
