### ISSUE TITLE
Does not apear to work for me

### ISSUE THREAD

**Issue by hannes-ucsc** [do-sch/gnome-shell-touchpad-window-move#2]
After installing this extension, three finger drags don't do anything. Ubuntu 19.10 on Dell XPS 7590. I don't see any errors in LookingGlass. Running `sudo libinput debug-events` gives

```
event10  POINTER_MOTION    +3.69s	  0.00/  0.88 ( +0.00/ +1.00)
 event10  POINTER_MOTION    +3.69s	  0.00/  0.88 ( +0.00/ +1.00)
```

for single finger drag,

```
 event10  POINTER_AXIS      +4.78s	vert 0.98/0* horiz 0.00/0 (finger)
 event10  POINTER_AXIS      +4.79s	vert 0.98/0* horiz 0.00/0 (finger)
```

for two finger drag and

```
 event10  GESTURE_SWIPE_BEGIN  +6.55s	3
 event10  GESTURE_SWIPE_UPDATE  +6.55s	3 -0.26/ 0.51 (-1.09/ 2.19 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.74s	3  0.00/ 0.10 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.76s	3  0.00/ 0.13 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.79s	3  0.15/ 0.15 ( 1.09/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.82s	3  0.00/ 0.14 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.82s	3  0.00/ 0.18 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.83s	3  0.00/ 0.22 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.84s	3  0.00/ 0.84 ( 0.00/ 3.28 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.84s	3  0.00/ 0.59 ( 0.00/ 2.19 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.85s	3  0.00/ 0.59 ( 0.00/ 2.19 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.86s	3  0.00/ 0.59 ( 0.00/ 2.19 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.87s	3  0.00/ 0.27 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.88s	3  0.00/ 0.19 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.95s	3  0.14/ 0.00 ( 1.09/ 0.00 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +6.99s	3  0.00/ 0.12 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +7.01s	3  0.00/ 0.14 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_UPDATE  +7.10s	3  0.00/ 0.13 ( 0.00/ 1.09 unaccelerated)
 event10  GESTURE_SWIPE_END  +7.95s	3
```

for a three finger drag.

Maybe it's a simple fix.

**Comment by hannes-ucsc** [comment]
I should also add that I virtually nothing about Gnome, Wayland, libinput and all that stuff ...

**Comment by do-sch** [comment]
The output shows, that three-finger gestures are recognized by libinput so it should not be a hardware issue.

1) Are you inside a wayland session? If wayland session failes, it'll automatically fallback to X11 without giving you any error message, even if Wayland is selected on login. You can verify with `echo $XDG_SESSION_TYPE` which protocol is used. If the output is `x11`, you'll need to figure out, why Wayland is not working four you. In my case Wayland is only working, if I use GDM as display manager. I once also had Wayland issues when using a Nvidia graphics card, which your notebook seems to have.

2) Was the pointer in front of a window, when you tried three-finger-gestures? The extension will only move windows, that are behind the pointer.

3) Are the default Gnome gestures working on your machine? Are workspaces switched, if you do a four finger drag? Is a three-finger-pinch showing your activities overview? Can you do a two-finger-pinch-to-zoom in eye-of-gnome and evince?
If those are working, can you give me the output of `journalctl -f /usr/bin/gnome-shell` when making touchpad gestures when the pointer is in front of windows and when it is in front of the desktop and other shell elements? It'll be an extension issue then.

4) Are there any other extensions enabled, that are doing something with input? There could also be a conflict.

**Comment by hannes-ucsc** [comment]
I feel so dumb now. I wasn't logged in with "Ubuntu on Wayland", just "Ubuntu" selected at the little cog icon on the login screen. Sorry for using up your time. Three finger drags work great now.
