### ISSUE TITLE
Won't load on GNOME Shell 3.36

### ISSUE THREAD

**Issue by brunelli** [do-sch/gnome-shell-touchpad-window-move#5]
`lg` shows the following: `TypeError: Clutter.DeviceManager is undefined`

**Comment by brunelli** [comment]
Relevant: [Introduce ClutterSeat and deprecate ClutterDeviceManager (#962) · Issues · GNOME / mutter · GitLab](https://gitlab.gnome.org/GNOME/mutter/issues/962)

My first attempt was unsuccessful, though:

```diff
-        const deviceManager = Clutter.DeviceManager.get_default();
-        this._virtualTouchpad = deviceManager.create_virtual_device(Clutter.InputDeviceType.TOUCHPAD_DEVICE);
-        this._virtualKeyboard = deviceManager.create_virtual_device(Clutter.InputDeviceType.KEYBOARD_DEVICE);
+        const backend = Clutter.get_default_backend();
+        const seat = backend.get_default_seat();
+        this._virtualTouchpad = seat.create_virtual_device(Clutter.InputDeviceType.TOUCHPAD_DEVICE);
+        this._virtualKeyboard = seat.create_virtual_device(Clutter.InputDeviceType.KEYBOARD_DEVICE);
```

**Comment by do-sch** [comment]
Thank you for the API-calls. It would probably have taken me hours to find them.

With TOUCHPAD_DEVICE as input device type my Shell keeps crashing with `meta_input_settings_get_tablet_wacom_device: assertion 'info != NULL' failed`.
Using POINTER_DEVICE shouldn't make a difference though.

It should be fixed now but it'll probably take some hours until the update arrives on the extension store.

**Comment by brunelli** [comment]
Thank you for this great extension!
