### ISSUE TITLE
Feature request: make the speed of the movement configurable

### ISSUE THREAD

**Issue by fmoralesc** [do-sch/gnome-shell-touchpad-window-move#9]
This is a very nice extension, but I think it would be useful to be able to configure the speed at which the movement goes, either by scaling the distances or by accelerating the movement.

**Comment by zsdiogo** [comment]
This would be great.

**Comment by do-sch** [comment]
Good idea. I think I'll implement that.

**Comment by do-sch** [comment]
It's on master now
